### ISSUE TITLE
[Feature Request] add fsr 1 scaler

### ISSUE THREAD

**Issue by Nerboruto** [PureDark/Skyrim-Upscaler#12]
on some gpu fsr 2 is too heavy and does not bring any benefit, on the contrary first fsr allows to obtain an improvement in visual quality without intensive use of the gpu.

**Comment by NightHammer1000** [comment]
If your GPU cant handle FSR2 it sure as hell cant handle Skyrim Special Edition.

**Comment by Nerboruto** [comment]
good boy!!! pity that skyrim special also runs on gt 710. furthermore fsr2 on several games i keep it disabled because i don't tolerate the temporal artifacts that i see. taa makes less artifacts than fsr2.1

**Comment by mhtvsSFrpHdE** [comment]
What are you looking for?

If quality, FSR 1 is just "compromised" lanczos, it's no good than original lanczos, just run faster.  
For me, the FSR 1 shall call "does not bring any benefit" because it doesn't use multi frame information.  
You can say FSR 1 is better than bicubic or bilinear, but it's still the same generation technic.  
And you can already get such thing from "magpie" or "Lossless Scaling" software,  
"Lossless Scaling" even contains a better than FSR 1 but consume less GPU single frame algorithm  
called "LS1 performance mode".

If performance, first you shouldn't try Special Edition, instead go 32 bit Direct X 9 old Skyrim.  
In that version, you have "Hialgo Boost" or "Hialgo Switch", which is allowing you to run 3D in 960x540,  
then use nearest algorithm to upscale 3D to 1920x1080 while keep UI render at 1920x1080.  
When nearest algorithm work on doubled resolution, it just works like integer upscale and give you sharp looking.  
And this algorithm run almost no cost, very fast.

FSR 2 series is to use the same principle like "Hialgo Switch" but replace single frame nearest to multiple frame algorithm.  
And support Direct X 11+ which is "Hialgo Switch" support only Direct X 9.

All single frame algorithm have no ability to erase flicker between frames when you are moving.  
That's what TAA and FSR 2 series do.  
In TAA, you can only take 1920x1080 and get 1920x1080, if give 960x540 you only get 960x540.  
In FSR 2, you take 960x540 or even 640x360 and get 1920x1080.  
If you run FSR 2 from 1920x1080 to 1920x1080,  
sure it will consume more resource than TAA and make you feel heavy.  
It just works in that way. Turn down your input resolution to dramatically reduce overall GPU cost.

**Comment by mhtvsSFrpHdE** [comment]
I ever run Witcher 3 next gen 4.0 update at "4K 60FPS" with entry level crap graphic card 1050 Ti.  
FSR 2 performance, input resolution 1280x720, upscale to 1920x1080,  
then use Lossless Scaling LS1 performance go from 1920x1080 to 3840x2160.

I don't agree the opinion says "FSR 2 is heavy".  
I not even use the "Ultra Performance" mode yet.

**Comment by Nerboruto** [comment]
well done you are a smart guy...
